### ISSUE TITLE
Implement list styling

### ISSUE THREAD

**Issue by kamil-perczynski** [kamil-perczynski/adoc-pdf-gen#4]
List stylesheets should have styles for nested lists.

Idea (similarly to headings):

```yaml
list:
  defaults:
    listSymbol: "▪"
    symbolIndent: 1rem
  level1:
    paragraph:
      spacingBefore: .75rem
      spacingAfter: .75rem
    listSymbol: "•"
  level2:
    listSymbol: "◦"
  level3:
    listSymbol: "▪"

```
